### ISSUE TITLE
Create server in Express

### ISSUE THREAD

**Issue by afeedhshaji** [CodeWizrd001/TodoApp#1]
https://github.com/CodeWizrd001/TodoApp/blob/cd643f8894ce009e7bb497698c6fa65725f5667e/bin/www#L22

Since we are already importing express, use the express-way of starting the server instead of nodes' ? Reduces a lot of code too.

Add this in `app.js`
```
const port = 3000;
app.listen(port, () => console.log(`App listening on port: ${port}`));
```

**Comment by CodeWizrd001** [comment]
www and app.js were generated by the express-generator tool 
We could eliminate those if it's overcomplicating
